/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IERC1155Token__factory } from "./IERC1155Token__factory";
export { IERC721Token__factory } from "./IERC721Token__factory";
